--- 
# database options: postgresql (default), mysql
database: postgresql
# exception options: exceptional (default), hoptoad
exception_handling: exceptional
# monitoring options: new_relic (default), scout
monitoring: new_relic