--- 
# rails options: any branch in the http://github.com/rails/rails/tree/master repo
rails_branch: 2-3-stable
# database options: postgresql (default), mysql
database: postgresql
# exception options: exceptional (default), hoptoad
exception_handling: exceptional
# monitoring options: new_relic (default), scout
monitoring: new_relic
# branches to create in the git repo. Default branch will be checked out.
# if none specified, just leaves the single master branch.
git_branches:
  master:
  development: default
  staging:
